<html>

<head>

<title>Fabricaide</title>

<link href="https://fonts.googleapis.com/css?family=Karla" rel="stylesheet">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<style type="text/css">
body {
  font-family: 'Karla', sans-serif;
}

form.addmaterial input {
  cursor: pointer;
}

form.addmaterial {
  display: inline-block;
  margin-top: 68px;
  margin-left: 10px;
}

h2 {
  margin-top: 70px;
  display: inline-block;
  vertical-align: top;
}

.title-link {
  text-decoration: none;
}

.title_link:visited {
  color: #000;
}

.wrapper {
  text-align:center;
}

.upload-btn-wrapper {
  position: relative;
  overflow: hidden;
  display: inline-block;
  text-align: center;
}

.btn {
  background-color: #f54531;
  border-radius: 20px;
  padding-top: 10px;
  padding-bottom: 10px;
  width: 300px;
  text-align:center;
  vertical-align: middle;
  color: #FFF;
  font-weight: bold;
  font-size: 26pt;
  display: inline-block;
  margin: 10px auto 0 auto;
  text-decoration: none;
  border: none;
  cursor: pointer;
}

.cancel-button {
  background-color: #f54531;
  border-radius: 20px;
  padding-top: 10px;
  padding-bottom: 10px;
  width: 300px;
  text-align:center;
  vertical-align: middle;
  color: #FFF;
  font-weight: bold;
  font-size: 26pt;
  display: inline-block;
  margin: 10px auto 0 auto;
  text-decoration: none;
  border: none;
}

.add-material {
  background-color: #69cf6d;
  border-radius: 10px;
  width: 32px;
  text-align:center;
  vertical-align: middle;
  color: #fff;
  font-weight: bold;
  font-size: 18pt;
  border: none;
}

.upload-button {
  margin-top: 47px;
}

label.options-label {
  margin: 0 10px 0 0;
  font-size: 24pt;
  font-weight: bold;
}

.material-options {
  width: 400px;
  height: 40px;
  font-size: 16pt;
  margin: 0 auto 10px auto;
}

.upload-btn-wrapper input[type=file] {
  font-size: 100px;
  position: absolute;
  left: 0;
  top: 0;
  opacity: 0;
  width:800px;
  height: 296px;
}

.instruction {
  font-weight: bold;
  font-size: 24pt;
  text-align: center;
  margin-bottom: 20px;
  max-width: 1200px;
  margin: 0 auto 10px auto;
}

.error {
  font-weight: bold;
  font-size: 32pt;
  text-align: center;
  margin-bottom: 20px;
  color: #F00;
}

.home-button {
  background-color: #f54531;
  border-radius: 20px;
  padding-top: 30px;
  padding-bottom: 30px;
  width: 400px;
  text-align:center;
  vertical-align: middle;
  color: #FFF;
  font-weight: bold;
  font-size: 32pt;
  line-height: 64px;
  display: block;
  margin: 0 auto;
  text-decoration: none;
}

.sheets {
  overflow-x: scroll;
  overflow-y: hidden;
  white-space: nowrap;
}

.sheets svg {
  display: inline-block;
  max-height: 200px;
  width: auto;
  border: 1px solid black;
}

.instruction-img svg {
  border: 1px solid black;
}

</style>


</head>

<body>


<div class="wrapper">
